language: python
python:
- '3.8'
cache:
- apt
- pip
sudo: false
dist: xenial
addons:
  apt:
    packages:
    - language-pack-en-base
before_install:
- openssl aes-256-cbc -K $encrypted_5a3a20ea2cb4_key -iv $encrypted_5a3a20ea2cb4_iv
  -in id_rsa.enc -out id_rsa -d
- git config --global user.name 'Differentiator'
- git config --global user.email 'invariantbuildbot@getnikola.com'
- git config --global push.default 'simple'
- pip install --upgrade-strategy eager -U pip wheel
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
install:
- pip install --upgrade pip setuptools wheel
- git clone https://github.com/getnikola/nikola -b master
- cd nikola
- pip install --upgrade-strategy eager -Ur requirements-extras.txt freezegun
- pip install .
script:
- scripts/baseline.sh build
after_success:
- echo -e 'Host gh\n    Host github.com\n    StrictHostKeyChecking no' >> ~/.ssh/config
- cd nikola-baseline-build/output
- git init .
- git checkout -b $(../../../getpyver.py)
- git remote add origin git@github.com:getnikola/invariant-builds.git
- git add .
- git commit -am "invariant build $(date) [ci skip]"
- git push --force origin $(../../../getpyver.py)
branches:
  only:
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#nikola
    template:
    - 'Invariant build by %{author}: %{message} See %{build_url}.'
    skip_join: false
    use_notice: true
