language: python
python:
- '2.7'
- '3.5'
sudo: false
addons:
  apt:
    packages:
    - language-pack-en-base
before_install:
- openssl aes-256-cbc -K $encrypted_5a3a20ea2cb4_key -iv $encrypted_5a3a20ea2cb4_iv
  -in id_rsa.enc -out id_rsa -d
- git config --global user.name 'Differentiator'
- git config --global user.email 'invariantbuildbot@getnikola.com'
- git config --global push.default 'simple'
- pip install pip wheel
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
install:
- wget https://github.com/getnikola/wheelhouse/archive/$(./getpyver.py).zip
- unzip $(./getpyver.py).zip
- pip install --upgrade pip setuptools
- pip install --use-wheel --no-index --find-links=wheelhouse-$(./getpyver.py short)
  lxml Pillow
- git clone https://github.com/getnikola/nikola -b $(./getdata.py branch)
- cd nikola
- pip install -r requirements-extras.txt freezegun
- pip install .
script:
- scripts/baseline.sh build
after_success:
- echo -e 'Host gh\n    Host github.com\n    StrictHostKeyChecking no' >> ~/.ssh/config
- cd nikola-baseline-build/output
- git init .
- git checkout -b $(../../../getpyver.py)
- git remote add origin git@github.com:getnikola/invariant-builds.git
- git add .
- git commit -am "invariant build $(date) [ci skip]"
- git push --force origin $(../../../getpyver.py)
notifications:
  irc:
    channels:
    - chat.freenode.net#nikola
    template:
    - 'Invariant build by %{author}: %{message} See %{build_url}.'
    skip_join: true
    use_notice: true
env:
  global:
    secure: Mf/FZd2ISNdfh7BqWKp6pXO5/K0hd0R86Ydn7F3IZLy7n9g7IhiulMpSuwSlchM7k8x1MwxAyBdxPPgUlgYNTSH5Wt5cI4CVZcRRPDq7sedXNiAMN6EMDYltrXS+2bjq5HbJ6m0hOrdsebcK/wDIQJUHuZ9KMG6k6XYjcUyXt8g=
