language: python
python:
- '2.7'
- '3.3'
before_install:
- git config --global user.name 'Differentiator'
- git config --global user.email 'invariantbuildbot@getnikola.com'
- git config --global push.default 'simple'
- pip install pycrypto pip wheel
- python decrypt_sshkey.py
- chmod 600 id_rsa
- eval $(ssh-agent)
- ssh-add id_rsa
- sudo apt-get --reinstall install -qq language-pack-en-base
install:
- wget https://github.com/getnikola/wheelhouse/archive/$(./getpyver.py).zip
- unzip $(./getpyver.py).zip
- pip install --use-wheel --no-index --find-links=wheelhouse-$(./getpyver.py short) lxml Pillow ipython
- git clone https://github.com/getnikola/nikola -b $(./getdata.py branch)
- cd nikola
- git checkout -qf $(./getdata.py commit)
- pip install -r requirements-tests.txt
- pip install .
script:
- nikola init --demo nikola-site
- cd nikola-site
- LC_ALL='en_US.UTF-8' python -c 'import locale; locale.setlocale(locale.LC_ALL, ("en_US", "utf8")); from nikola.__main__ import main; exit(main(["build", "--invariant"]))'
after_success:
- echo -e 'Host gh\n    Host github.com\n    StrictHostKeyChecking no' >> ~/.ssh/config
- cd output
- git init .
- git checkout -b $(../../../getpyver.py)
- git remote add origin git@github.com:getnikola/invariant-builds.git
- git add .
- git commit -am "invariant build $(date) [ci skip]"
- git push --force origin $(../../../getpyver.py)
notifications:
  irc:
    channels:
    - chat.freenode.net#nikola
    template:
    - 'Invariant build by %{author}: %{message} See %{build_url}.'
env:
  global:
    secure: Mf/FZd2ISNdfh7BqWKp6pXO5/K0hd0R86Ydn7F3IZLy7n9g7IhiulMpSuwSlchM7k8x1MwxAyBdxPPgUlgYNTSH5Wt5cI4CVZcRRPDq7sedXNiAMN6EMDYltrXS+2bjq5HbJ6m0hOrdsebcK/wDIQJUHuZ9KMG6k6XYjcUyXt8g=
