name: Trigger an update
on:
  workflow_dispatch:
    inputs:
     commit_message:
        description: "Reason for rebuild (commit message)"
        required: true

jobs:
  trigger:
    name: Trigger an update
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
            ref: master
      - name: Update file
        run: |
            python -c "num = int(open('BUILD-DATA', 'r').read().strip().split(':')[1].strip()); open('BUILD-DATA', 'w').write('build-number: {0}{1}'.format(num + 1, chr(0x0a)))"
      - name: Push to GitHub
        run: |
          git config --global user.name '${{ github.actor }} (via bot)'
          git config --global user.email 'invariantbuildbot@getnikola.com'
          git config --global push.default 'simple'
          git checkout master
          git remote rm origin
          git remote add origin "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git"
          git status
          git add .
          git status
          git commit -am "${{ github.event.inputs.commit_message }}"
          git push origin master
